---
- name: Install docker
  action: "{{ ansible_pkg_mgr }} name=docker state=latest"

- name: Enable docker
  service:
    name: docker
    enabled: yes
    state: started

- name: Add docker group
  group:
    name: docker
    state: present
  notify: restart docker

- name: Install Git
  action: "{{ ansible_pkg_mgr }} name=git state=latest"
