---

- import_playbook: ../prep.yml
  tags:
  - 'never'
  - 'install'

- import_playbook: ../osp/manage-user-network.yml
  when:
  - hosting_infrastructure == 'openstack'
  tags:
  - 'never'
  - 'install'

- import_playbook: ../osp/provision-osp-instance.yml
  when:
  - hosting_infrastructure == 'openstack'
  tags:
  - 'never'
  - 'install'

- import_playbook: ../rhsm.yml
  tags:
  - 'never'
  - 'install'

- hosts: dns-server
  roles:
  - role: update-host
  tags:
  - 'never'
  - 'install'

- import_playbook: configure-dns-server.yml
  tags:
  - 'always'
